name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag interview:$(date +%s)
    
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
  
  login-and-push:
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to JFrog
      uses: docker/login-action@v1
      with:
        registry: interviewtest.jfrog.io
        username: ${{ secrets.JFROG_USER }}
        password: ${{ secrets.JFROG_PASS }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: interviewtest.jfrog.io/docker/interview:latest
