name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag interview:$(date +%s)
    
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3.1.0
    
    -
      name: Login to JFrog
      uses: docker/login-action@v1
      with:
        registry: interviewtest.jfrog.io
        username: ${{ secrets.JFROG_USER }}
        password: ${{ secrets.JFROG_PASS }}
